type token =
  | EMPTY
  | LIBERTY_ATTRENUM_address
  | LIBERTY_ATTRENUM_address_width
  | LIBERTY_ATTRENUM_area
  | LIBERTY_ATTRENUM_area_coefficient
  | LIBERTY_ATTRENUM_auxiliary_pad_cell
  | LIBERTY_ATTRENUM_base_curves_group
  | LIBERTY_ATTRENUM_base_curve_type
  | LIBERTY_ATTRENUM_base_type
  | LIBERTY_ATTRENUM_bit_from
  | LIBERTY_ATTRENUM_bit_to
  | LIBERTY_ATTRENUM_bit_width
  | LIBERTY_ATTRENUM_bus_naming_style
  | LIBERTY_ATTRENUM_bus_type
  | LIBERTY_ATTRENUM_calc_mode
  | LIBERTY_ATTRENUM_capacitance
  | LIBERTY_ATTRENUM_capacitive_load_unit
  | LIBERTY_ATTRENUM_cell_footprint
  | LIBERTY_ATTRENUM_cell_leakage_power
  | LIBERTY_ATTRENUM_cell_name
  | LIBERTY_ATTRENUM_clear
  | LIBERTY_ATTRENUM_clear_preset_var1
  | LIBERTY_ATTRENUM_clear_preset_var2
  | LIBERTY_ATTRENUM_clock
  | LIBERTY_ATTRENUM_clocked_on
  | LIBERTY_ATTRENUM_clocked_on_also
  | LIBERTY_ATTRENUM_clock_gate_clock_pin
  | LIBERTY_ATTRENUM_clock_gate_enable_pin
  | LIBERTY_ATTRENUM_clock_gate_obs_pin
  | LIBERTY_ATTRENUM_clock_gate_out_pin
  | LIBERTY_ATTRENUM_clock_gate_test_pin
  | LIBERTY_ATTRENUM_clock_gating_flag
  | LIBERTY_ATTRENUM_clock_gating_integrated_cell
  | LIBERTY_ATTRENUM_clock_pin
  | LIBERTY_ATTRENUM_coefs
  | LIBERTY_ATTRENUM_column_address
  | LIBERTY_ATTRENUM_comment
  | LIBERTY_ATTRENUM_complementary_pin
  | LIBERTY_ATTRENUM_connection_class
  | LIBERTY_ATTRENUM_constraint
  | LIBERTY_ATTRENUM_constraint_high
  | LIBERTY_ATTRENUM_constraint_low
  | LIBERTY_ATTRENUM_contention_condition
  | LIBERTY_ATTRENUM_current_unit
  | LIBERTY_ATTRENUM_curve_id
  | LIBERTY_ATTRENUM_curve_x
  | LIBERTY_ATTRENUM_curve_y
  | LIBERTY_ATTRENUM_data_in
  | LIBERTY_ATTRENUM_data_type
  | LIBERTY_ATTRENUM_date
  | LIBERTY_ATTRENUM_dcm_timing
  | LIBERTY_ATTRENUM_default_cell_failure_rate
  | LIBERTY_ATTRENUM_default_cell_leakage_power
  | LIBERTY_ATTRENUM_default_connection_class
  | LIBERTY_ATTRENUM_default_edge_rate_breakpoint_f0
  | LIBERTY_ATTRENUM_default_edge_rate_breakpoint_f1
  | LIBERTY_ATTRENUM_default_edge_rate_breakpoint_r0
  | LIBERTY_ATTRENUM_default_edge_rate_breakpoint_r1
  | LIBERTY_ATTRENUM_default_fall_delay_intercept
  | LIBERTY_ATTRENUM_default_fall_pin_resistance
  | LIBERTY_ATTRENUM_default_fanout_load
  | LIBERTY_ATTRENUM_default_hold_coefficient
  | LIBERTY_ATTRENUM_default_inout_pin_cap
  | LIBERTY_ATTRENUM_default_inout_pin_fall_res
  | LIBERTY_ATTRENUM_default_inout_pin_rise_res
  | LIBERTY_ATTRENUM_default_input_pin_cap
  | LIBERTY_ATTRENUM_default_intrinsic_fall
  | LIBERTY_ATTRENUM_default_intrinsic_rise
  | LIBERTY_ATTRENUM_default_leakage_power_density
  | LIBERTY_ATTRENUM_default_max_capacitance
  | LIBERTY_ATTRENUM_default_max_fanout
  | LIBERTY_ATTRENUM_default_max_transition
  | LIBERTY_ATTRENUM_default_max_utilization
  | LIBERTY_ATTRENUM_default_min_porosity
  | LIBERTY_ATTRENUM_default_operating_conditions
  | LIBERTY_ATTRENUM_default_output_pin_cap
  | LIBERTY_ATTRENUM_default_output_pin_fall_res
  | LIBERTY_ATTRENUM_default_output_pin_rise_res
  | LIBERTY_ATTRENUM_default_power_rail
  | LIBERTY_ATTRENUM_default_rc_fall_coefficient
  | LIBERTY_ATTRENUM_default_rc_rise_coefficient
  | LIBERTY_ATTRENUM_default_reference_capacitance
  | LIBERTY_ATTRENUM_default_rise_delay_intercept
  | LIBERTY_ATTRENUM_default_rise_pin_resistance
  | LIBERTY_ATTRENUM_default_setup_coefficient
  | LIBERTY_ATTRENUM_default_slope_fall
  | LIBERTY_ATTRENUM_default_slope_rise
  | LIBERTY_ATTRENUM_default_threshold_voltage_group
  | LIBERTY_ATTRENUM_default_timing
  | LIBERTY_ATTRENUM_default_wire_load
  | LIBERTY_ATTRENUM_default_wire_load_area
  | LIBERTY_ATTRENUM_default_wire_load_capacitance
  | LIBERTY_ATTRENUM_default_wire_load_mode
  | LIBERTY_ATTRENUM_default_wire_load_resistance
  | LIBERTY_ATTRENUM_default_wire_load_selection
  | LIBERTY_ATTRENUM_define_cell_area
  | LIBERTY_ATTRENUM_delay_model
  | LIBERTY_ATTRENUM_direction
  | LIBERTY_ATTRENUM_divided_by
  | LIBERTY_ATTRENUM_dont_fault
  | LIBERTY_ATTRENUM_dont_touch
  | LIBERTY_ATTRENUM_dont_use
  | LIBERTY_ATTRENUM_downto
  | LIBERTY_ATTRENUM_drive_current
  | LIBERTY_ATTRENUM_driver_type
  | LIBERTY_ATTRENUM_driver_waveform
  | LIBERTY_ATTRENUM_driver_waveform_fall
  | LIBERTY_ATTRENUM_driver_waveform_name
  | LIBERTY_ATTRENUM_driver_waveform_rise
  | LIBERTY_ATTRENUM_duty_cycle
  | LIBERTY_ATTRENUM_edge_rate_breakpoint_f0
  | LIBERTY_ATTRENUM_edge_rate_breakpoint_f1
  | LIBERTY_ATTRENUM_edge_rate_breakpoint_r0
  | LIBERTY_ATTRENUM_edge_rate_breakpoint_r1
  | LIBERTY_ATTRENUM_edge_rate_fall
  | LIBERTY_ATTRENUM_edge_rate_load_fall
  | LIBERTY_ATTRENUM_edge_rate_load_rise
  | LIBERTY_ATTRENUM_edge_rate_rise
  | LIBERTY_ATTRENUM_edge_rate_sensitivity_f0
  | LIBERTY_ATTRENUM_edge_rate_sensitivity_f1
  | LIBERTY_ATTRENUM_edge_rate_sensitivity_r0
  | LIBERTY_ATTRENUM_edge_rate_sensitivity_r1
  | LIBERTY_ATTRENUM_edges
  | LIBERTY_ATTRENUM_edge_type
  | LIBERTY_ATTRENUM_em_temp_degradation_factor
  | LIBERTY_ATTRENUM_enable
  | LIBERTY_ATTRENUM_enable_also
  | LIBERTY_ATTRENUM_equal_or_opposite_output
  | LIBERTY_ATTRENUM_failure_rate
  | LIBERTY_ATTRENUM_fall_capacitance
  | LIBERTY_ATTRENUM_fall_capacitance_range
  | LIBERTY_ATTRENUM_fall_current_slope_after_threshold
  | LIBERTY_ATTRENUM_fall_current_slope_before_threshold
  | LIBERTY_ATTRENUM_fall_delay_intercept
  | LIBERTY_ATTRENUM_falling_together_group
  | LIBERTY_ATTRENUM_fall_pin_resistance
  | LIBERTY_ATTRENUM_fall_resistance
  | LIBERTY_ATTRENUM_fall_time_after_threshold
  | LIBERTY_ATTRENUM_fall_time_before_threshold
  | LIBERTY_ATTRENUM_fanout_area
  | LIBERTY_ATTRENUM_fanout_capacitance
  | LIBERTY_ATTRENUM_fanout_length
  | LIBERTY_ATTRENUM_fanout_load
  | LIBERTY_ATTRENUM_fanout_resistance
  | LIBERTY_ATTRENUM_faster_factor
  | LIBERTY_ATTRENUM_fault_model
  | LIBERTY_ATTRENUM_force_00
  | LIBERTY_ATTRENUM_force_01
  | LIBERTY_ATTRENUM_force_10
  | LIBERTY_ATTRENUM_force_11
  | LIBERTY_ATTRENUM_force_inverter_removal
  | LIBERTY_ATTRENUM_fpga_allow_duplicate_degenerated_gates
  | LIBERTY_ATTRENUM_fpga_bridge_inputs
  | LIBERTY_ATTRENUM_fpga_cell_type
  | LIBERTY_ATTRENUM_fpga_complex_degenerate
  | LIBERTY_ATTRENUM_fpga_degenerate_output
  | LIBERTY_ATTRENUM_fpga_family
  | LIBERTY_ATTRENUM_fpga_lut_insert_before_sequential
  | LIBERTY_ATTRENUM_fpga_lut_output
  | LIBERTY_ATTRENUM_fpga_max_degen_input_size
  | LIBERTY_ATTRENUM_fpga_min_degen_input_size
  | LIBERTY_ATTRENUM_fpga_prefer_undegenerated_gates
  | LIBERTY_ATTRENUM_fpga_timing_type
  | LIBERTY_ATTRENUM_fsim_map
  | LIBERTY_ATTRENUM_function
  | LIBERTY_ATTRENUM_geometry_print
  | LIBERTY_ATTRENUM_handle_negative_constraint
  | LIBERTY_ATTRENUM_has_builtin_pad
  | LIBERTY_ATTRENUM_height_coefficient
  | LIBERTY_ATTRENUM_high
  | LIBERTY_ATTRENUM_hold_coefficient
  | LIBERTY_ATTRENUM_hysteresis
  | LIBERTY_ATTRENUM_ignore_verify_icg_type
  | LIBERTY_ATTRENUM_index_1
  | LIBERTY_ATTRENUM_index_2
  | LIBERTY_ATTRENUM_index_3
  | LIBERTY_ATTRENUM_index_4
  | LIBERTY_ATTRENUM_index_output
  | LIBERTY_ATTRENUM_in_place_swap_mode
  | LIBERTY_ATTRENUM_input_high_value
  | LIBERTY_ATTRENUM_input_low_value
  | LIBERTY_ATTRENUM_input_map
  | LIBERTY_ATTRENUM_input_map_shift
  | LIBERTY_ATTRENUM_input_pins
  | LIBERTY_ATTRENUM_input_signal_level
  | LIBERTY_ATTRENUM_input_signal_level_high
  | LIBERTY_ATTRENUM_input_signal_level_low
  | LIBERTY_ATTRENUM_input_switching_condition
  | LIBERTY_ATTRENUM_input_threshold_pct_fall
  | LIBERTY_ATTRENUM_input_threshold_pct_rise
  | LIBERTY_ATTRENUM_input_voltage
  | LIBERTY_ATTRENUM_input_voltage_range
  | LIBERTY_ATTRENUM_interdependence_id
  | LIBERTY_ATTRENUM_interface_timing
  | LIBERTY_ATTRENUM_intermediate_values
  | LIBERTY_ATTRENUM_internal_node
  | LIBERTY_ATTRENUM_intrinsic_fall
  | LIBERTY_ATTRENUM_intrinsic_rise
  | LIBERTY_ATTRENUM_invert
  | LIBERTY_ATTRENUM_inverted_output
  | LIBERTY_ATTRENUM_is_clock_gating_cell
  | LIBERTY_ATTRENUM_is_inverting
  | LIBERTY_ATTRENUM_is_isolation_cell
  | LIBERTY_ATTRENUM_is_level_shifter
  | LIBERTY_ATTRENUM_is_needed
  | LIBERTY_ATTRENUM_isolation_cell_data_pin
  | LIBERTY_ATTRENUM_isolation_cell_enable_pin
  | LIBERTY_ATTRENUM_is_pad
  | LIBERTY_ATTRENUM_is_three_state
  | LIBERTY_ATTRENUM_key_bit
  | LIBERTY_ATTRENUM_key_feature
  | LIBERTY_ATTRENUM_key_file
  | LIBERTY_ATTRENUM_key_seed
  | LIBERTY_ATTRENUM_key_version
  | LIBERTY_ATTRENUM_k_process_cell_degradation
  | LIBERTY_ATTRENUM_k_process_cell_fall
  | LIBERTY_ATTRENUM_k_process_cell_leakage_power
  | LIBERTY_ATTRENUM_k_process_cell_rise
  | LIBERTY_ATTRENUM_k_process_drive_current
  | LIBERTY_ATTRENUM_k_process_drive_fall
  | LIBERTY_ATTRENUM_k_process_drive_rise
  | LIBERTY_ATTRENUM_k_process_fall_delay_intercept
  | LIBERTY_ATTRENUM_k_process_fall_pin_resistance
  | LIBERTY_ATTRENUM_k_process_fall_propagation
  | LIBERTY_ATTRENUM_k_process_fall_transition
  | LIBERTY_ATTRENUM_k_process_hold_fall
  | LIBERTY_ATTRENUM_k_process_hold_rise
  | LIBERTY_ATTRENUM_k_process_internal_power
  | LIBERTY_ATTRENUM_k_process_intrinsic_fall
  | LIBERTY_ATTRENUM_k_process_intrinsic_rise
  | LIBERTY_ATTRENUM_k_process_min_period
  | LIBERTY_ATTRENUM_k_process_min_pulse_width_high
  | LIBERTY_ATTRENUM_k_process_min_pulse_width_low
  | LIBERTY_ATTRENUM_k_process_nochange_fall
  | LIBERTY_ATTRENUM_k_process_nochange_rise
  | LIBERTY_ATTRENUM_k_process_pin_cap
  | LIBERTY_ATTRENUM_k_process_pin_fall_cap
  | LIBERTY_ATTRENUM_k_process_pin_rise_cap
  | LIBERTY_ATTRENUM_k_process_recovery_fall
  | LIBERTY_ATTRENUM_k_process_recovery_rise
  | LIBERTY_ATTRENUM_k_process_removal_fall
  | LIBERTY_ATTRENUM_k_process_removal_rise
  | LIBERTY_ATTRENUM_k_process_rise_delay_intercept
  | LIBERTY_ATTRENUM_k_process_rise_pin_resistance
  | LIBERTY_ATTRENUM_k_process_rise_propagation
  | LIBERTY_ATTRENUM_k_process_rise_transition
  | LIBERTY_ATTRENUM_k_process_setup_fall
  | LIBERTY_ATTRENUM_k_process_setup_rise
  | LIBERTY_ATTRENUM_k_process_skew_fall
  | LIBERTY_ATTRENUM_k_process_skew_rise
  | LIBERTY_ATTRENUM_k_process_slope_fall
  | LIBERTY_ATTRENUM_k_process_slope_rise
  | LIBERTY_ATTRENUM_k_process_wire_cap
  | LIBERTY_ATTRENUM_k_process_wire_res
  | LIBERTY_ATTRENUM_k_temp_cell_degradation
  | LIBERTY_ATTRENUM_k_temp_cell_fall
  | LIBERTY_ATTRENUM_k_temp_cell_leakage_power
  | LIBERTY_ATTRENUM_k_temp_cell_rise
  | LIBERTY_ATTRENUM_k_temp_drive_current
  | LIBERTY_ATTRENUM_k_temp_drive_fall
  | LIBERTY_ATTRENUM_k_temp_drive_rise
  | LIBERTY_ATTRENUM_k_temp_fall_delay_intercept
  | LIBERTY_ATTRENUM_k_temp_fall_pin_resistance
  | LIBERTY_ATTRENUM_k_temp_fall_propagation
  | LIBERTY_ATTRENUM_k_temp_fall_transition
  | LIBERTY_ATTRENUM_k_temp_hold_fall
  | LIBERTY_ATTRENUM_k_temp_hold_rise
  | LIBERTY_ATTRENUM_k_temp_internal_power
  | LIBERTY_ATTRENUM_k_temp_intrinsic_fall
  | LIBERTY_ATTRENUM_k_temp_intrinsic_rise
  | LIBERTY_ATTRENUM_k_temp_min_period
  | LIBERTY_ATTRENUM_k_temp_min_pulse_width_high
  | LIBERTY_ATTRENUM_k_temp_min_pulse_width_low
  | LIBERTY_ATTRENUM_k_temp_nochange_fall
  | LIBERTY_ATTRENUM_k_temp_nochange_rise
  | LIBERTY_ATTRENUM_k_temp_pin_cap
  | LIBERTY_ATTRENUM_k_temp_recovery_fall
  | LIBERTY_ATTRENUM_k_temp_recovery_rise
  | LIBERTY_ATTRENUM_k_temp_removal_fall
  | LIBERTY_ATTRENUM_k_temp_removal_rise
  | LIBERTY_ATTRENUM_k_temp_rise_delay_intercept
  | LIBERTY_ATTRENUM_k_temp_rise_pin_resistance
  | LIBERTY_ATTRENUM_k_temp_rise_propagation
  | LIBERTY_ATTRENUM_k_temp_rise_transition
  | LIBERTY_ATTRENUM_k_temp_setup_fall
  | LIBERTY_ATTRENUM_k_temp_setup_rise
  | LIBERTY_ATTRENUM_k_temp_skew_fall
  | LIBERTY_ATTRENUM_k_temp_skew_rise
  | LIBERTY_ATTRENUM_k_temp_slope_fall
  | LIBERTY_ATTRENUM_k_temp_slope_rise
  | LIBERTY_ATTRENUM_k_temp_wire_cap
  | LIBERTY_ATTRENUM_k_temp_wire_res
  | LIBERTY_ATTRENUM_k_volt_cell_degradation
  | LIBERTY_ATTRENUM_k_volt_cell_fall
  | LIBERTY_ATTRENUM_k_volt_cell_leakage_power
  | LIBERTY_ATTRENUM_k_volt_cell_rise
  | LIBERTY_ATTRENUM_k_volt_drive_current
  | LIBERTY_ATTRENUM_k_volt_drive_fall
  | LIBERTY_ATTRENUM_k_volt_drive_rise
  | LIBERTY_ATTRENUM_k_volt_fall_delay_intercept
  | LIBERTY_ATTRENUM_k_volt_fall_pin_resistance
  | LIBERTY_ATTRENUM_k_volt_fall_propagation
  | LIBERTY_ATTRENUM_k_volt_fall_transition
  | LIBERTY_ATTRENUM_k_volt_hold_fall
  | LIBERTY_ATTRENUM_k_volt_hold_rise
  | LIBERTY_ATTRENUM_k_volt_internal_power
  | LIBERTY_ATTRENUM_k_volt_intrinsic_fall
  | LIBERTY_ATTRENUM_k_volt_intrinsic_rise
  | LIBERTY_ATTRENUM_k_volt_min_period
  | LIBERTY_ATTRENUM_k_volt_min_pulse_width_high
  | LIBERTY_ATTRENUM_k_volt_min_pulse_width_low
  | LIBERTY_ATTRENUM_k_volt_nochange_fall
  | LIBERTY_ATTRENUM_k_volt_nochange_rise
  | LIBERTY_ATTRENUM_k_volt_pin_cap
  | LIBERTY_ATTRENUM_k_volt_recovery_fall
  | LIBERTY_ATTRENUM_k_volt_recovery_rise
  | LIBERTY_ATTRENUM_k_volt_removal_fall
  | LIBERTY_ATTRENUM_k_volt_removal_rise
  | LIBERTY_ATTRENUM_k_volt_rise_delay_intercept
  | LIBERTY_ATTRENUM_k_volt_rise_pin_resistance
  | LIBERTY_ATTRENUM_k_volt_rise_propagation
  | LIBERTY_ATTRENUM_k_volt_rise_transition
  | LIBERTY_ATTRENUM_k_volt_setup_fall
  | LIBERTY_ATTRENUM_k_volt_setup_rise
  | LIBERTY_ATTRENUM_k_volt_skew_fall
  | LIBERTY_ATTRENUM_k_volt_skew_rise
  | LIBERTY_ATTRENUM_k_volt_slope_fall
  | LIBERTY_ATTRENUM_k_volt_slope_rise
  | LIBERTY_ATTRENUM_k_volt_wire_cap
  | LIBERTY_ATTRENUM_k_volt_wire_res
  | LIBERTY_ATTRENUM_leakage_power_unit
  | LIBERTY_ATTRENUM_level_shifter_data_pin
  | LIBERTY_ATTRENUM_level_shifter_enable_pin
  | LIBERTY_ATTRENUM_level_shifter_type
  | LIBERTY_ATTRENUM_library_features
  | LIBERTY_ATTRENUM_low
  | LIBERTY_ATTRENUM_lsi_pad
  | LIBERTY_ATTRENUM_lsi_pad_fall
  | LIBERTY_ATTRENUM_lsi_pad_rise
  | LIBERTY_ATTRENUM_lsi_rounding_cutoff
  | LIBERTY_ATTRENUM_lsi_rounding_digit
  | LIBERTY_ATTRENUM_map_only
  | LIBERTY_ATTRENUM_mapping
  | LIBERTY_ATTRENUM_map_to_logic
  | LIBERTY_ATTRENUM_master_pin
  | LIBERTY_ATTRENUM_max_capacitance
  | LIBERTY_ATTRENUM_max_fanout
  | LIBERTY_ATTRENUM_max_input_noise_width
  | LIBERTY_ATTRENUM_max_time_borrow
  | LIBERTY_ATTRENUM_max_transition
  | LIBERTY_ATTRENUM_members
  | LIBERTY_ATTRENUM_miller_cap_fall
  | LIBERTY_ATTRENUM_miller_cap_rise
  | LIBERTY_ATTRENUM_min_capacitance
  | LIBERTY_ATTRENUM_min_fanout
  | LIBERTY_ATTRENUM_min_input_noise_width
  | LIBERTY_ATTRENUM_min_period
  | LIBERTY_ATTRENUM_min_pulse_width_high
  | LIBERTY_ATTRENUM_min_pulse_width_low
  | LIBERTY_ATTRENUM_min_transition
  | LIBERTY_ATTRENUM_mode
  | LIBERTY_ATTRENUM_mpm_libname
  | LIBERTY_ATTRENUM_mpm_name
  | LIBERTY_ATTRENUM_multicell_pad_pin
  | LIBERTY_ATTRENUM_multiplied_by
  | LIBERTY_ATTRENUM_next_state
  | LIBERTY_ATTRENUM_nextstate_type
  | LIBERTY_ATTRENUM_nom_calc_mode
  | LIBERTY_ATTRENUM_nominal_va_values
  | LIBERTY_ATTRENUM_nom_process
  | LIBERTY_ATTRENUM_nom_temperature
  | LIBERTY_ATTRENUM_nom_voltage
  | LIBERTY_ATTRENUM_observe_node
  | LIBERTY_ATTRENUM_orders
  | LIBERTY_ATTRENUM_output_signal_level
  | LIBERTY_ATTRENUM_output_signal_level_high
  | LIBERTY_ATTRENUM_output_signal_level_low
  | LIBERTY_ATTRENUM_output_switching_condition
  | LIBERTY_ATTRENUM_output_threshold_pct_fall
  | LIBERTY_ATTRENUM_output_threshold_pct_rise
  | LIBERTY_ATTRENUM_output_voltage
  | LIBERTY_ATTRENUM_output_voltage_range
  | LIBERTY_ATTRENUM_pad_cell
  | LIBERTY_ATTRENUM_pad_type
  | LIBERTY_ATTRENUM_parameter1
  | LIBERTY_ATTRENUM_parameter2
  | LIBERTY_ATTRENUM_parameter3
  | LIBERTY_ATTRENUM_parameter4
  | LIBERTY_ATTRENUM_parameter5
  | LIBERTY_ATTRENUM_pg_function
  | LIBERTY_ATTRENUM_pg_type
  | LIBERTY_ATTRENUM_piece_define
  | LIBERTY_ATTRENUM_piece_type
  | LIBERTY_ATTRENUM_pin_equal
  | LIBERTY_ATTRENUM_pin_func_type
  | LIBERTY_ATTRENUM_pin_name_map
  | LIBERTY_ATTRENUM_pin_names
  | LIBERTY_ATTRENUM_pin_opposite
  | LIBERTY_ATTRENUM_poly_convert
  | LIBERTY_ATTRENUM_power_down_function
  | LIBERTY_ATTRENUM_power_gating_cell
  | LIBERTY_ATTRENUM_power_gating_pin
  | LIBERTY_ATTRENUM_power_level
  | LIBERTY_ATTRENUM_power_model
  | LIBERTY_ATTRENUM_power_rail
  | LIBERTY_ATTRENUM_preferred
  | LIBERTY_ATTRENUM_preferred_input_pad_voltage
  | LIBERTY_ATTRENUM_preferred_output_pad_slew_rate_control
  | LIBERTY_ATTRENUM_preferred_output_pad_voltage
  | LIBERTY_ATTRENUM_prefer_tied
  | LIBERTY_ATTRENUM_preset
  | LIBERTY_ATTRENUM_primary_output
  | LIBERTY_ATTRENUM_process
  | LIBERTY_ATTRENUM_pulling_current
  | LIBERTY_ATTRENUM_pulling_resistance
  | LIBERTY_ATTRENUM_pulling_resistance_unit
  | LIBERTY_ATTRENUM_rail_connection
  | LIBERTY_ATTRENUM_reference_capacitance
  | LIBERTY_ATTRENUM_reference_time
  | LIBERTY_ATTRENUM_related_bus_equivalent
  | LIBERTY_ATTRENUM_related_bus_pins
  | LIBERTY_ATTRENUM_related_falling_pin
  | LIBERTY_ATTRENUM_related_ground_pin
  | LIBERTY_ATTRENUM_related_input
  | LIBERTY_ATTRENUM_related_inputs
  | LIBERTY_ATTRENUM_related_internal_pg_pin
  | LIBERTY_ATTRENUM_related_output
  | LIBERTY_ATTRENUM_related_output_pin
  | LIBERTY_ATTRENUM_related_outputs
  | LIBERTY_ATTRENUM_related_pg_pin
  | LIBERTY_ATTRENUM_related_pin
  | LIBERTY_ATTRENUM_related_power_pin
  | LIBERTY_ATTRENUM_related_rising_pin
  | LIBERTY_ATTRENUM_related_switch_pin
  | LIBERTY_ATTRENUM_resistance
  | LIBERTY_ATTRENUM_resistance_unit
  | LIBERTY_ATTRENUM_retention_cell
  | LIBERTY_ATTRENUM_retention_pin
  | LIBERTY_ATTRENUM_revision
  | LIBERTY_ATTRENUM_rise_capacitance
  | LIBERTY_ATTRENUM_rise_capacitance_range
  | LIBERTY_ATTRENUM_rise_current_slope_after_threshold
  | LIBERTY_ATTRENUM_rise_current_slope_before_threshold
  | LIBERTY_ATTRENUM_rise_delay_intercept
  | LIBERTY_ATTRENUM_rise_pin_resistance
  | LIBERTY_ATTRENUM_rise_resistance
  | LIBERTY_ATTRENUM_rise_time_after_threshold
  | LIBERTY_ATTRENUM_rise_time_before_threshold
  | LIBERTY_ATTRENUM_rising_together_group
  | LIBERTY_ATTRENUM_routing_layers
  | LIBERTY_ATTRENUM_row_address
  | LIBERTY_ATTRENUM_scaling_factors
  | LIBERTY_ATTRENUM_scan_group
  | LIBERTY_ATTRENUM_sdf_cond
  | LIBERTY_ATTRENUM_sdf_cond_end
  | LIBERTY_ATTRENUM_sdf_cond_start
  | LIBERTY_ATTRENUM_sdf_edges
  | LIBERTY_ATTRENUM_sensitization_master
  | LIBERTY_ATTRENUM_set_node
  | LIBERTY_ATTRENUM_setup_coefficient
  | LIBERTY_ATTRENUM_shifts
  | LIBERTY_ATTRENUM_short
  | LIBERTY_ATTRENUM_signal_type
  | LIBERTY_ATTRENUM_simulation
  | LIBERTY_ATTRENUM_single_bit_degenerate
  | LIBERTY_ATTRENUM_slew_control
  | LIBERTY_ATTRENUM_slew_derate_from_library
  | LIBERTY_ATTRENUM_slew_lower_threshold_pct_fall
  | LIBERTY_ATTRENUM_slew_lower_threshold_pct_rise
  | LIBERTY_ATTRENUM_slew_upper_threshold_pct_fall
  | LIBERTY_ATTRENUM_slew_upper_threshold_pct_rise
  | LIBERTY_ATTRENUM_slope
  | LIBERTY_ATTRENUM_slope_fall
  | LIBERTY_ATTRENUM_slope_rise
  | LIBERTY_ATTRENUM_slower_factor
  | LIBERTY_ATTRENUM_stage_type
  | LIBERTY_ATTRENUM_state_function
  | LIBERTY_ATTRENUM_std_cell_main_rail
  | LIBERTY_ATTRENUM_steady_state_resistance_above_high
  | LIBERTY_ATTRENUM_steady_state_resistance_below_low
  | LIBERTY_ATTRENUM_steady_state_resistance_float_max
  | LIBERTY_ATTRENUM_steady_state_resistance_float_min
  | LIBERTY_ATTRENUM_steady_state_resistance_high
  | LIBERTY_ATTRENUM_steady_state_resistance_high_max
  | LIBERTY_ATTRENUM_steady_state_resistance_high_min
  | LIBERTY_ATTRENUM_steady_state_resistance_low
  | LIBERTY_ATTRENUM_steady_state_resistance_low_max
  | LIBERTY_ATTRENUM_steady_state_resistance_low_min
  | LIBERTY_ATTRENUM_switch_cell_type
  | LIBERTY_ATTRENUM_switch_function
  | LIBERTY_ATTRENUM_switching_interval
  | LIBERTY_ATTRENUM_switching_together_group
  | LIBERTY_ATTRENUM_switch_pin
  | LIBERTY_ATTRENUM_table
  | LIBERTY_ATTRENUM_tdisable
  | LIBERTY_ATTRENUM_technology
  | LIBERTY_ATTRENUM_temperature
  | LIBERTY_ATTRENUM_test_output_only
  | LIBERTY_ATTRENUM_three_state
  | LIBERTY_ATTRENUM_threshold
  | LIBERTY_ATTRENUM_threshold_voltage_group
  | LIBERTY_ATTRENUM_tied_off
  | LIBERTY_ATTRENUM_time_unit
  | LIBERTY_ATTRENUM_timing_model_type
  | LIBERTY_ATTRENUM_timing_report
  | LIBERTY_ATTRENUM_timing_sense
  | LIBERTY_ATTRENUM_timing_type
  | LIBERTY_ATTRENUM_total_track_area
  | LIBERTY_ATTRENUM_tracks
  | LIBERTY_ATTRENUM_tree_type
  | LIBERTY_ATTRENUM_type
  | LIBERTY_ATTRENUM_typical_capacitances
  | LIBERTY_ATTRENUM_use_for_size_only
  | LIBERTY_ATTRENUM_user_function_class
  | LIBERTY_ATTRENUM_value
  | LIBERTY_ATTRENUM_values
  | LIBERTY_ATTRENUM_va_parameters
  | LIBERTY_ATTRENUM_variable_1
  | LIBERTY_ATTRENUM_variable_1_range
  | LIBERTY_ATTRENUM_variable_2
  | LIBERTY_ATTRENUM_variable_2_range
  | LIBERTY_ATTRENUM_variable_3
  | LIBERTY_ATTRENUM_variable_3_range
  | LIBERTY_ATTRENUM_variable_4
  | LIBERTY_ATTRENUM_variable_4_range
  | LIBERTY_ATTRENUM_variable_5_range
  | LIBERTY_ATTRENUM_variable_6_range
  | LIBERTY_ATTRENUM_variable_7_range
  | LIBERTY_ATTRENUM_variables
  | LIBERTY_ATTRENUM_va_values
  | LIBERTY_ATTRENUM_vector
  | LIBERTY_ATTRENUM_vhdl_name
  | LIBERTY_ATTRENUM_vih
  | LIBERTY_ATTRENUM_vil
  | LIBERTY_ATTRENUM_vimax
  | LIBERTY_ATTRENUM_vimin
  | LIBERTY_ATTRENUM_voh
  | LIBERTY_ATTRENUM_vol
  | LIBERTY_ATTRENUM_voltage
  | LIBERTY_ATTRENUM_voltage_map
  | LIBERTY_ATTRENUM_voltage_name
  | LIBERTY_ATTRENUM_voltage_unit
  | LIBERTY_ATTRENUM_vomax
  | LIBERTY_ATTRENUM_vomin
  | LIBERTY_ATTRENUM_wave_fall
  | LIBERTY_ATTRENUM_wave_rise
  | LIBERTY_ATTRENUM_when
  | LIBERTY_ATTRENUM_when_end
  | LIBERTY_ATTRENUM_when_start
  | LIBERTY_ATTRENUM_width_coefficient
  | LIBERTY_ATTRENUM_wire_load_from_area
  | LIBERTY_ATTRENUM_word_width
  | LIBERTY_ATTRENUM_x_function
  | LIBERTY_ATTRENUM_xnf_device_name
  | LIBERTY_ATTRENUM_xnf_schnm
  | LIBERTY_GROUPENUM_base_curves
  | LIBERTY_GROUPENUM_bundle
  | LIBERTY_GROUPENUM_bus
  | LIBERTY_GROUPENUM_capacitance
  | LIBERTY_GROUPENUM_ccs_lu_table_template
  | LIBERTY_GROUPENUM_ccsn_first_stage
  | LIBERTY_GROUPENUM_ccsn_last_stage
  | LIBERTY_GROUPENUM_ccs_timing_base_curve
  | LIBERTY_GROUPENUM_ccs_timing_base_curve_template
  | LIBERTY_GROUPENUM_cell
  | LIBERTY_GROUPENUM_cell_degradation
  | LIBERTY_GROUPENUM_cell_fall
  | LIBERTY_GROUPENUM_cell_fall_to_pct
  | LIBERTY_GROUPENUM_cell_rise
  | LIBERTY_GROUPENUM_cell_rise_to_pct
  | LIBERTY_GROUPENUM_compact_ccs_fall
  | LIBERTY_GROUPENUM_compact_ccs_rise
  | LIBERTY_GROUPENUM_compact_lut_template
  | LIBERTY_GROUPENUM_compressed_ccs_timing_rise
  | LIBERTY_GROUPENUM_dc_current
  | LIBERTY_GROUPENUM_domain
  | LIBERTY_GROUPENUM_dynamic_current
  | LIBERTY_GROUPENUM_electromigration
  | LIBERTY_GROUPENUM_em_lut_template
  | LIBERTY_GROUPENUM_em_max_toggle_rate
  | LIBERTY_GROUPENUM_fall_capacitance
  | LIBERTY_GROUPENUM_fall_capacitance_range
  | LIBERTY_GROUPENUM_fall_constraint
  | LIBERTY_GROUPENUM_fall_net_delay
  | LIBERTY_GROUPENUM_fall_power
  | LIBERTY_GROUPENUM_fall_propagation
  | LIBERTY_GROUPENUM_fall_transition
  | LIBERTY_GROUPENUM_fall_transition_degradation
  | LIBERTY_GROUPENUM_ff
  | LIBERTY_GROUPENUM_ff_bank
  | LIBERTY_GROUPENUM_gate_leakage
  | LIBERTY_GROUPENUM_generated_clock
  | LIBERTY_GROUPENUM_hyperbolic_noise_above_high
  | LIBERTY_GROUPENUM_hyperbolic_noise_below_low
  | LIBERTY_GROUPENUM_hyperbolic_noise_high
  | LIBERTY_GROUPENUM_hyperbolic_noise_low
  | LIBERTY_GROUPENUM_init_current
  | LIBERTY_GROUPENUM_input_signal_swing
  | LIBERTY_GROUPENUM_input_voltage
  | LIBERTY_GROUPENUM_interconnect_delay
  | LIBERTY_GROUPENUM_internal_power
  | LIBERTY_GROUPENUM_intrinsic_capacitance
  | LIBERTY_GROUPENUM_intrinsic_parasitic
  | LIBERTY_GROUPENUM_intrinsic_resistance
  | LIBERTY_GROUPENUM_iv_lut_template
  | LIBERTY_GROUPENUM_latch
  | LIBERTY_GROUPENUM_latch_bank
  | LIBERTY_GROUPENUM_leakage_current
  | LIBERTY_GROUPENUM_leakage_power
  | LIBERTY_GROUPENUM_left_id
  | LIBERTY_GROUPENUM_library
  | LIBERTY_GROUPENUM_lower
  | LIBERTY_GROUPENUM_lut
  | LIBERTY_GROUPENUM_lu_table_template
  | LIBERTY_GROUPENUM_max_cap
  | LIBERTY_GROUPENUM_maxcap_lut_template
  | LIBERTY_GROUPENUM_max_trans
  | LIBERTY_GROUPENUM_maxtrans_lut_template
  | LIBERTY_GROUPENUM_memory
  | LIBERTY_GROUPENUM_memory_read
  | LIBERTY_GROUPENUM_memory_write
  | LIBERTY_GROUPENUM_minimum_period
  | LIBERTY_GROUPENUM_min_pulse_width
  | LIBERTY_GROUPENUM_mode_definition
  | LIBERTY_GROUPENUM_model
  | LIBERTY_GROUPENUM_mode_value
  | LIBERTY_GROUPENUM_noise_immunity_above_high
  | LIBERTY_GROUPENUM_noise_immunity_below_low
  | LIBERTY_GROUPENUM_noise_immunity_high
  | LIBERTY_GROUPENUM_noise_immunity_low
  | LIBERTY_GROUPENUM_noise_lut_template
  | LIBERTY_GROUPENUM_normalized_driver_waveform
  | LIBERTY_GROUPENUM_operating_conditions
  | LIBERTY_GROUPENUM_output_current_fall
  | LIBERTY_GROUPENUM_output_current_rise
  | LIBERTY_GROUPENUM_output_current_template
  | LIBERTY_GROUPENUM_output_signal_swing
  | LIBERTY_GROUPENUM_output_voltage
  | LIBERTY_GROUPENUM_output_voltage_fall
  | LIBERTY_GROUPENUM_output_voltage_rise
  | LIBERTY_GROUPENUM_peak_current
  | LIBERTY_GROUPENUM_peak_time
  | LIBERTY_GROUPENUM_peak_voltage
  | LIBERTY_GROUPENUM_pg_current
  | LIBERTY_GROUPENUM_pg_current_template
  | LIBERTY_GROUPENUM_pg_pin
  | LIBERTY_GROUPENUM_pin
  | LIBERTY_GROUPENUM_pin_based_variation
  | LIBERTY_GROUPENUM_pin_capacitance
  | LIBERTY_GROUPENUM_poly_template
  | LIBERTY_GROUPENUM_power
  | LIBERTY_GROUPENUM_power_lut_template
  | LIBERTY_GROUPENUM_power_poly_template
  | LIBERTY_GROUPENUM_power_supply
  | LIBERTY_GROUPENUM_propagated_noise_height_above_high
  | LIBERTY_GROUPENUM_propagated_noise_height_below_low
  | LIBERTY_GROUPENUM_propagated_noise_height_high
  | LIBERTY_GROUPENUM_propagated_noise_height_low
  | LIBERTY_GROUPENUM_propagated_noise_high
  | LIBERTY_GROUPENUM_propagated_noise_low
  | LIBERTY_GROUPENUM_propagated_noise_peak_time_ratio_above_high
  | LIBERTY_GROUPENUM_propagated_noise_peak_time_ratio_below_low
  | LIBERTY_GROUPENUM_propagated_noise_peak_time_ratio_high
  | LIBERTY_GROUPENUM_propagated_noise_peak_time_ratio_low
  | LIBERTY_GROUPENUM_propagated_noise_width_above_high
  | LIBERTY_GROUPENUM_propagated_noise_width_below_low
  | LIBERTY_GROUPENUM_propagated_noise_width_high
  | LIBERTY_GROUPENUM_propagated_noise_width_low
  | LIBERTY_GROUPENUM_propagation_lut_template
  | LIBERTY_GROUPENUM_receiver_capacitance
  | LIBERTY_GROUPENUM_receiver_capacitance1_fall
  | LIBERTY_GROUPENUM_receiver_capacitance1_rise
  | LIBERTY_GROUPENUM_receiver_capacitance2_fall
  | LIBERTY_GROUPENUM_receiver_capacitance2_rise
  | LIBERTY_GROUPENUM_retain_fall_slew
  | LIBERTY_GROUPENUM_retaining_fall
  | LIBERTY_GROUPENUM_retaining_rise
  | LIBERTY_GROUPENUM_retain_rise_slew
  | LIBERTY_GROUPENUM_right_id
  | LIBERTY_GROUPENUM_rise_capacitance
  | LIBERTY_GROUPENUM_rise_capacitance_range
  | LIBERTY_GROUPENUM_rise_constraint
  | LIBERTY_GROUPENUM_rise_net_delay
  | LIBERTY_GROUPENUM_rise_power
  | LIBERTY_GROUPENUM_rise_propagation
  | LIBERTY_GROUPENUM_rise_transition
  | LIBERTY_GROUPENUM_rise_transition_degradation
  | LIBERTY_GROUPENUM_routing_track
  | LIBERTY_GROUPENUM_scaled_cell
  | LIBERTY_GROUPENUM_scaling_factors
  | LIBERTY_GROUPENUM_sensitization
  | LIBERTY_GROUPENUM_seq
  | LIBERTY_GROUPENUM_seq_bank
  | LIBERTY_GROUPENUM_state
  | LIBERTY_GROUPENUM_statetable
  | LIBERTY_GROUPENUM_steady_state_current_high
  | LIBERTY_GROUPENUM_steady_state_current_low
  | LIBERTY_GROUPENUM_steady_state_current_tristate
  | LIBERTY_GROUPENUM_switching_group
  | LIBERTY_GROUPENUM_test_cell
  | LIBERTY_GROUPENUM_timing
  | LIBERTY_GROUPENUM_timing_based_variation
  | LIBERTY_GROUPENUM_timing_range
  | LIBERTY_GROUPENUM_tlatch
  | LIBERTY_GROUPENUM_type
  | LIBERTY_GROUPENUM_upper
  | LIBERTY_GROUPENUM_user_parameters
  | LIBERTY_GROUPENUM_va_compact_ccs_fall
  | LIBERTY_GROUPENUM_va_compact_ccs_rise
  | LIBERTY_GROUPENUM_va_fall_constraint
  | LIBERTY_GROUPENUM_va_receiver_capacitance1_fall
  | LIBERTY_GROUPENUM_va_receiver_capacitance1_rise
  | LIBERTY_GROUPENUM_va_receiver_capacitance2_fall
  | LIBERTY_GROUPENUM_va_receiver_capacitance2_rise
  | LIBERTY_GROUPENUM_va_rise_constraint
  | LIBERTY_GROUPENUM_vector
  | LIBERTY_GROUPENUM_wire_load
  | LIBERTY_GROUPENUM_wire_load_selection
  | LIBERTY_GROUPENUM_wire_load_table
  | COMMA
  | SEMI
  | LPAR
  | RPAR
  | LCURLY
  | RCURLY
  | COLON
  | KW_DEFINE
  | KW_DEFINE_GROUP
  | KW_TRUE
  | KW_FALSE
  | PLUS
  | MINUS
  | MULT
  | DIV
  | EQ
  | SIMPLE
  | HEAD
  | ATTR
  | KW_FLOAT
  | KW_STRING
  | KW_ENUM
  | KW_INTEGER
  | KW_SHORT
  | KW_OR
  | KW_AND
  | KW_BOOLEAN
  | KW_LIST
  | LBRACK
  | RBRACK
  | INCLUDE
  | ENDOFFILE
  | UNARY
  | NUM of (float)
  | STRING of (string)
  | ID of (string)
  | DOUBLE of (token*token)
  | TRIPLE of (token*token*token)
  | QUADRUPLE of (token*token*token*token)
  | QUINTUPLE of (token*token*token*token*token)
  | SEXTUPLE of (token*token*token*token*token*token)
  | SEPTUPLE of (token*token*token*token*token*token*token)
  | OCTUPLE of (token*token*token*token*token*token*token*token)

val file :
  (Lexing.lexbuf  -> token) -> Lexing.lexbuf -> token
